<?php

namespace LibraryBundle\Repository;

/**
 * etatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etatRepository extends \Doctrine\ORM\EntityRepository
{
}
